apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"
    shortNames:
    - mr
  versions: 
  - name: "v1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            # x-kubernetes-validation-rules:
            #   - rule: ".*:.*"
            #     message: "image must contain tag"
            #   - rule: "^(?!(.*:latest$)).*$"
            #     message: "image should not end with tag: latest"
            type: object
            required: ["image","owner","locale"]
            properties:
              image:
                type: "string"
                # pattern: '^(?!(.*:latest$)).*$'
              owner:
                type: "string"
                pattern: '^org.io/'
              locale:
                type: "string"
                enum:
                - EN
                - DE
